//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CX418DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ID { get; set; }
        public string EventName { get; set; }
        public Nullable<bool> MultiRace { get; set; }
        public Nullable<bool> MultiDay { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public System.DateTime StartDay { get; set; }
        public System.DateTime EndDay { get; set; }
        public string Description { get; set; }
    }
}
