//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CX418DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LapTime
    {
        public int ID { get; set; }
        public string bib { get; set; }
        public Nullable<int> LapTime1 { get; set; }
        public int RaceId { get; set; }
        public System.DateTime LapEndTime { get; set; }
        public Nullable<int> LapNumber { get; set; }
        public Nullable<int> CurrentRaceTime { get; set; }
    }
}
